### ISSUE TITLE
Grundpaket: Wagon erstellen

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito_ejv#4]
Ein neuer Wagon "hitobito_ejv-afy"

https://github.com/hitobito/hitobito/blob/master/doc/development/04_wagons.md

**Comment by kronn** [comment]
Siehe 8b2aed60e0ae03d9e4870bfb90d6a1a3742f3018 und 7da66599fad0c1b33bb45780491dc03bd96a78af

**Comment by TheWalkingLeek** [comment]
Schaut gut aus
