### ISSUE TITLE
Grundpaket: Anpassungen am Design

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito_ejv#6]
- [x] Farbschema
   - Weiss-Rot, analog https://www.jodlerverband.ch/de/
   - Rot = #c3130b
- [x] Logo
   - see: https://files.puzzle.ch/apps/files/files/7120189?dir=/swe/projects/EJV_Jodlerverband/Projektdaten
- [x] Schriftart
   - Arial
- [x] weitere SCSS-Anpassungen

**Comment by kronn** [comment]
See https://github.com/hitobito/hitobito_ejv/commit/ab9d7756e960b9cbe4161af3f2f5d0a2f4f0e6c1

**Comment by TheWalkingLeek** [comment]
Auf Int getestet, schaut gut aus
